### ISSUE TITLE
Should all styles be opaque?

### ISSUE THREAD

**Issue by meetar** [tangrams/refill#26]
Investigating this issue: https://github.com/tangrams/differ/issues/10 I discovered that at least one of the refill draw styles is partially transparent, and relying on the canvas `background-color` for proper coloring:

<img width="727" alt="screen shot 2016-10-28 at 1 24 00 pm" src="https://cloud.githubusercontent.com/assets/459970/19815695/112b8ff6-9d12-11e6-92eb-09102c892c00.png">

Is there a benefit to transparency here? Would it be better for the basemap to be completely opaque?

**Comment by nvkelso** [comment]
@patriciogonzalezvivo would know more why that dot pattern is transparent. 

But for allowing data "underlays", a transparent option is a good thing.

**Comment by patriciogonzalezvivo** [comment]
As far as I can see, this line https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L951 is not necessary and is setting alpha channel to `0.0`

**Comment by patriciogonzalezvivo** [comment]
In some tangram blocks I leave the open the option of having **alpha** and **transparency**. Why? well, in the case of  [`polygons-diagonal-stripes` ](http://tangrams.github.io/blocks/#polygons-diagonal-stripes) it have been prove for me that this is a fast way to apply an effect to a type of `landuse` while let you see the treatment of the `earth` layer under it. 

![screen shot 2016-10-31 at 2 14 49 pm](https://cloud.githubusercontent.com/assets/346914/19865893/7f049fe0-9f74-11e6-81af-b453195fb2ae.png)

[Hill shading in TRON2](https://tangrams.github.io/tron-style/#16.526368634665808/37.79975/-122.47005) is a good example of that. There is a catch on it... you have to set the `blend` mode to something else that the default blending style... other wise is `blended` against the `background-color` of the canvas context.

Refill, seams to have old `styles` from a pre`tangram/blocks` era... where all this (and other) problems were addresses.

**Comment by nvkelso** [comment]
@meetar can you test this against @sensescape's latest roads-refactor branch to see if it's still an issue, please?

**Comment by meetar** [comment]
@nvkelso All clear!

![image](https://cloud.githubusercontent.com/assets/459970/24933355/ec9a2c66-1ee3-11e7-9aeb-da924883e6c0.png)

**Comment by nvkelso** [comment]
Closing as config changed, thanks for checking!

**Comment by sensescape** [comment]
Thanks @meetar !
