### ISSUE TITLE
Labels on landuse pattern getting cut off

### ISSUE THREAD

**Issue by sensescape** [tangrams/refill#31]
http://tangrams.github.io/refill-style/#8/36.671/-117.922

<img width="840" alt="screen shot 2016-12-12 at 11 44 46 am" src="https://cloud.githubusercontent.com/assets/466585/21114017/8f622698-c060-11e6-8d03-01dbbc5ec4dc.png">

**Comment by nvkelso** [comment]
@bcamper Did this change recently?

**Comment by bcamper** [comment]
Not intentionally :)  But could see it having been a casualty of either some optimizations we made to shader rendering (maybe a state change is being missed) or fixes to alpha blending. I'll look into it.

**Comment by sensescape** [comment]
Adding a stroke/halo to the text fixes it:
<img width="868" alt="screen shot 2016-12-12 at 3 24 31 pm" src="https://cloud.githubusercontent.com/assets/466585/21121064/37fa0672-c07f-11e6-95bf-1db3ead0bb1d.png">

but text looks like this sometimes, over landuse pattern:
<img width="142" alt="screen shot 2016-12-12 at 3 25 54 pm" src="https://cloud.githubusercontent.com/assets/466585/21121091/61ee960a-c07f-11e6-99e3-d6af4de3d5d8.png">

<img width="191" alt="screen shot 2016-12-12 at 3 27 07 pm" src="https://cloud.githubusercontent.com/assets/466585/21121124/7fef6378-c07f-11e6-9101-9b88e5034748.png">

**Comment by bcamper** [comment]
@patriciogonzalezvivo I haven't looked at this yet, but for the bottom example, with text over the dot pattern: do you think the alpha is interacting weirdly with the shader perhaps? Could you see what alpha is output from the shader?

**Comment by patriciogonzalezvivo** [comment]
Weird... all this dot patterns don't have alpha: https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L1126-L1194 ... @sensescape do you know what `layer` or landuse style is interfering with what label layer ??

**Comment by patriciogonzalezvivo** [comment]
My apologize, @bcamper point that alpha is affected in this line https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L1141
I'm not sure why we were multiplying the alpha there... but I think doing this is better:

```yaml
                color: |
                    color.rgb = mix(COLOR1, COLOR2, circle(tile(getTileCoords(),PATTERN_SCALE), DOT_SIZE));
```

The `DOT_SIZE` define should need to be adjusted.

Also as @bcamper point we should use a texture here... `aastep` which is use by `circle` was some performance cost... 

Happy to introduce any of those changes: a. simplify the shader as is... b. replace it for a texture

**Note**: I feel that using a shader will be only justifiable if we want to apply a hill-shade effect using the dot size, like we did in TRON2.0

![screen shot 2016-12-14 at 11 18 46 am](https://cloud.githubusercontent.com/assets/346914/21190252/2f79d63c-c1ef-11e6-94be-153d2c6084f4.png)
 
Also switching to tangram blocks will solve more of this kind of issues... some of the shader in this style are quite old. For example the above code have been improved before here http://tangrams.github.io/blocks/#polygons-dots

**Comment by patriciogonzalezvivo** [comment]
Another example of dots for hill-shading https://tangrams.github.io/tangram-sandbox/tangram.html?styles/callejas#16.764280621970464/37.79126/-122.46361

![screen shot 2016-12-14 at 11 22 44 am](https://cloud.githubusercontent.com/assets/346914/21190424/b076e07c-c1ef-11e6-9e2a-216a9b7d6fd2.png)

**Comment by patriciogonzalezvivo** [comment]
So... I fix the bug by avoiding using the alpha channel... this was the effect of making the dots a little bigger, because the alpha was "eating" the texture more than is colorated (alpha interpolation is different). Any how now `DOT_SIZE` need adjustments.  @sensescape could you tweak it until makes sense for you.

Once that's done, and we have parameters we are happy with I can make texture of them : )

**Comment by bcamper** [comment]
@sensescape: @patriciogonzalezvivo put the fix on the gh-pages branch, so you should see it once this gets merged there (or you could merge it back here but may just make things more complicated):

https://github.com/tangrams/refill-style/commit/46b60c06b4acd53dbd003d7b950bc08ab349dafa

**Comment by patriciogonzalezvivo** [comment]
thanks! and sorry for that

**Comment by bcamper** [comment]
@sensescape I want to look into the issue with the California label (the original issue): can you show me the commit where you added the stroke, so I can compare before/after?

**Comment by sensescape** [comment]
@bcamper sure, it's here on this branch:
https://github.com/tangrams/refill-style/tree/sensescape/places-refactor

**Comment by sensescape** [comment]
this is the default text stroke that fixed it:
https://github.com/tangrams/refill-style/blob/sensescape/places-refactor/refill-style.yaml#L4108

**Comment by sensescape** [comment]
thanks! @patriciogonzalezvivo 
I'm tweaking dots pattern on places-refactor branch : )

**Comment by bcamper** [comment]
Actually it looks like the original problem was the same thing with weird alpha on the underlying dots shader, so it should also be fixed (if you want to remove the stroke later) by the same fix for that.

**Comment by sensescape** [comment]
ok! thanks : )

**Comment by bcamper** [comment]
Closing original issue, added #32 to optimize dot shaders to use textures instead as follow-up (which @patriciogonzalezvivo and I discussed).
