### ISSUE TITLE
Roads layer refactor

### ISSUE THREAD

**Issue by nvkelso** [tangrams/refill#37]
Especially road text label sizes (smaller than 11 pt is probably too small), maybe add one way arrows?

**Comment by nvkelso** [comment]
@sensescape I think this one is done – though I'm not sure about status of tiny road label size?

**Comment by sensescape** [comment]
yes this is done

https://github.com/tangrams/refill-style/commit/ea196468d750e88e94fa14d50f5bc54a0593826f

we have one-way arrows now!

<img width="977" alt="screen shot 2017-04-07 at 9 03 40 am" src="https://cloud.githubusercontent.com/assets/466585/24930718/5bf53ecc-1ebf-11e7-8d9f-477db38ecfb8.png">
