### ISSUE TITLE
Set up building grid pattern for global color

### ISSUE THREAD

**Issue by sensescape** [tangrams/refill#41]
I've set up Refill to use global colors, so that we can easily switch color schemes.

<img width="537" alt="screen shot 2017-03-09 at 4 13 37 pm" src="https://cloud.githubusercontent.com/assets/466585/23777008/a1146994-04e6-11e7-978c-3ce62f83a0c3.png">

Started a branch: 
https://github.com/tangrams/refill-style/tree/sensescape/roads-refactor

Global colors are set here:
https://github.com/tangrams/refill-style/blob/sensescape/roads-refactor/refill-style.yaml#L260-L288

But need help passing global color to some of the shaders, is there a way to set a global color for the building grid? or do we just swap building grid textures?

Looks like this now:
<img width="784" alt="screen shot 2017-03-09 at 4 23 50 pm" src="https://cloud.githubusercontent.com/assets/466585/23777072/069722b6-04e7-11e7-9341-fb8c8f6dfc88.png">

Texture img:
https://github.com/tangrams/refill-style/blob/sensescape/roads-refactor/refill-style.yaml#L727-L730

Shader:
https://github.com/tangrams/refill-style/blob/sensescape/roads-refactor/refill-style.yaml#L1280-L1297

**Comment by patriciogonzalezvivo** [comment]
Hi @sensescape, happy to help you in this one. This looks fantastic! We have to ways to go with it, I think, passing the color as the building color (but the background will always be white)... or using `uniforms` like @bcamper suggest. The second one is better if you want to be changing more than one color, like for example bg vs fg.

My second question is about the rgb2hsd and then the hsd2rgb... is a little expensive to do this on all the pixels of the building geometry... we could calculate that directly on the JS code if you want... is there any reson to do hue tinting instead of passing the value in RGB?

**Comment by sensescape** [comment]
Thanks @patriciogonzalezvivo ! Actually we dont need the rgb2hsd and then the hsd2rgb at all, it's copy pasted from bubble wrap ;)

**Comment by sensescape** [comment]
Yes the 2nd option, where you can change both bg and fg with globals

**Comment by patriciogonzalezvivo** [comment]
cool! Should I make a PR for that or commit directly in your brunch? any way is fine for me

**Comment by patriciogonzalezvivo** [comment]
So here is a solution https://github.com/tangrams/refill-style/commit/a960984db701bb0c836e549de088cb78320f6e28

the white of the roof and walls is pass as the building color. And the grid foreground as a uniform... that way we save up uniforms. Just as a future note, if the background is going to be always white we should use the geometry color for the grid, using uniforms could run into resources problems in the long run. : )

**Comment by nvkelso** [comment]
Into the branch works for us :)

**Comment by patriciogonzalezvivo** [comment]
done! there : )

**Comment by sensescape** [comment]
Thanks @patriciogonzalezvivo ! 
: )

<img width="989" alt="screen shot 2017-03-10 at 3 00 56 pm" src="https://cloud.githubusercontent.com/assets/466585/23816585/782b1af2-05a2-11e7-9bb2-efbaeee1b2ca.png">

**Comment by patriciogonzalezvivo** [comment]
WOW!!!
