### ISSUE TITLE
Coloring road shields and other icons

### ISSUE THREAD

**Issue by sensescape** [tangrams/refill#43]
@nvkelso @bcamper 

What is the best way to easily swap colors for road shields?

The first technique I tried, was converting all the road shields to white in Illustrator, and then specifying the color in the yaml:
<img width="647" alt="screen shot 2017-04-04 at 2 45 26 pm" src="https://cloud.githubusercontent.com/assets/466585/24680699/d3d85362-1946-11e7-9061-6720b180699e.png">

But this result is not that great. It's not so legible.

Is there a way for me to keep the white and still be able to specify the border color to blue or pink?

(Trying to avoid having a large sprite sheet with road shields in all colors too)

This is how road shields look right now, without any customization of color:
<img width="590" alt="screen shot 2017-04-04 at 2 59 43 pm" src="https://cloud.githubusercontent.com/assets/466585/24680859/713228e0-1947-11e7-8cde-71faf6265a9e.png">

**Comment by bcamper** [comment]
Hmm let me give that one some thought to see if there's a way to leverage existing styling.

**Comment by nvkelso** [comment]
Look at that curved El Camino Real label, am I right!?

**Comment by nvkelso** [comment]
There's probably something in @patriciogonzalezvivo's https://github.com/tangrams/refill-style/pull/45/commits/a960984db701bb0c836e549de088cb78320f6e28 for building texture recoloring we can apply to road shield recoloring (and to all the other sprites, for that matter).

**Comment by bcamper** [comment]
Try this: e6d41aefa82857dccb757306f0eb2c4a2535aa65

**Comment by nvkelso** [comment]
Mostly working, but followup discussion in comment https://github.com/tangrams/refill-style/commit/e6d41aefa82857dccb757306f0eb2c4a2535aa65#commitcomment-21760298.

**Comment by nvkelso** [comment]
@sensescape Can this issue be closed?

**Comment by sensescape** [comment]
yes looks good
<img width="550" alt="screen shot 2017-04-17 at 1 06 06 pm" src="https://cloud.githubusercontent.com/assets/466585/25107330/87e6a890-2383-11e7-8e2f-28f8bcd63546.png">
<img width="619" alt="screen shot 2017-04-17 at 1 04 38 pm" src="https://cloud.githubusercontent.com/assets/466585/25107331/87e904dc-2383-11e7-9c05-6bfb0bd8bc79.png">
