### ISSUE TITLE
Uniforms with random for shader texture

### ISSUE THREAD

**Issue by sensescape** [tangrams/refill#44]
@bcamper @nvkelso 

I was able to color this texture, but how do I create uniforms when I use random values?
<img width="808" alt="screen shot 2017-04-04 at 4 16 43 pm" src="https://cloud.githubusercontent.com/assets/466585/24683132/217e938c-1952-11e7-94a2-0f1290b347af.png">

<img width="886" alt="screen shot 2017-04-04 at 4 20 35 pm" src="https://cloud.githubusercontent.com/assets/466585/24683215/ac2f84dc-1952-11e7-9c50-496c6198a339.png">

https://github.com/tangrams/refill-style/blob/e86ad2f414fc785906387f24c86878da3084e9b2/refill-style.yaml#L1083-L1084

**Comment by sensescape** [comment]
this is done

adding u_tint to gray pattern

<img width="729" alt="screen shot 2017-04-11 at 2 04 44 pm" src="https://cloud.githubusercontent.com/assets/466585/24930853/dc01a858-1ebf-11e7-9299-e99ce17f7e27.png">


https://github.com/tangrams/refill-style/commit/ea196468d750e88e94fa14d50f5bc54a0593826f

**Comment by bcamper** [comment]
Is it still grey in some places, or am I imagining that? (And/or maybe
intended)

**Comment by sensescape** [comment]
made some tweaks, had to lighten the gray and add a darker color tint, here's the new version:

<img width="937" alt="screen shot 2017-04-11 at 5 08 23 pm" src="https://cloud.githubusercontent.com/assets/466585/24935870/9a4985e2-1ed9-11e7-8b8a-2c4b32755104.png">

a little hint of gray, but mostly working
![refill-pixel-tint](https://cloud.githubusercontent.com/assets/466585/24935912/0588a8e2-1eda-11e7-8ee4-ef92db4725f9.png)

**Comment by nvkelso** [comment]
@bcamper is there a way to make the random affect the value, but not
saturation or hue?

**Comment by bcamper** [comment]
@sensescape made some additional tweaks and we think the grey is gone now
