### ISSUE TITLE
Add color variants to Refill for data visualization

### ISSUE THREAD

**Issue by nvkelso** [tangrams/refill#46]
Via SDK option:

- [x] Black (default)
- [x] Grey (OpenTraffic work)
- [x] Pink
- [x] Blue
- [x] Sepiatone
- [ ] ~~¿Shaded relief?~~

**Comment by nvkelso** [comment]
Splitting off shaded relief for later followup in https://github.com/tangrams/refill-style/issues/50.

**Comment by nvkelso** [comment]
@sensescape is this ready to close?

**Comment by sensescape** [comment]
yes this is done
