### ISSUE TITLE
2 building grid shaders - new white grid shader added

### ISSUE THREAD

**Issue by sensescape** [tangrams/refill#55]
@bcamper @nvkelso 

Hi @bcamper ! I need help with this shader.
I'm adding a second building-grid shader, where the grid color is white
https://github.com/tangrams/refill-style/blob/f58319b373eee93acf88571f5b4b3283162b33b1/theme/color.yaml#L312

But right now, it ignores the 2nd custom shader I created
https://github.com/tangrams/refill-style/blob/f58319b373eee93acf88571f5b4b3283162b33b1/theme/color.yaml#L304-L320

Looks like this right now:
![tangram-19-40 71364--74 00141-20170518137](https://cloud.githubusercontent.com/assets/466585/26221508/a0343cc2-3bcb-11e7-9991-18f2e75878ee.png)

I wanted the generic buildings to have the dark grid, and all the colored buildings to have a white grid:
https://github.com/tangrams/refill-style/blob/f58319b373eee93acf88571f5b4b3283162b33b1/theme/color.yaml#L81-L192

**Comment by sensescape** [comment]
@nvkelso @bcamper 
I'd like a white grid like this:
<img width="257" alt="screen shot 2017-05-18 at 1 15 55 pm" src="https://cloud.githubusercontent.com/assets/466585/26221685/41e189f8-3bcc-11e7-81cf-56aec9ebaea3.png">

Thanks!

**Comment by sensescape** [comment]
Also, what if I have 2 textures, one light and one bold:
https://github.com/tangrams/refill-style/blob/sensescape/roads-refactor/theme/color.yaml#L355-L360

**Comment by bcamper** [comment]
Hey @sensescape, can you help me understand where it is failing to do what you want? In the examples above, the purple and orange buildings have the white grid, and in the first one, it seems like the other buildings have the old black grid. Where is the problem manifesting?

**Comment by sensescape** [comment]
@bcamper 
![zoom-bldg](https://cloud.githubusercontent.com/assets/466585/26223860/dab54d74-3bd4-11e7-95fc-c0b2f926fc71.png)

the pink building has a dark grid, i'm trying to make the grid white with this shader:
https://github.com/tangrams/refill-style/blob/10da9f9c61b40da33d156bcde4bf41e934ad97bb/theme/color.yaml#L305-L321

and all the colored buildings as well, trying to make the grid white too

**Comment by sensescape** [comment]
@bcamper 
more examples from tokyo
<img width="417" alt="screen shot 2017-05-18 at 2 25 54 pm" src="https://cloud.githubusercontent.com/assets/466585/26224155/ff7c0ce6-3bd5-11e7-937d-0d770b3e5e42.png">
http://localhost:8000/#16/35.6863/139.7663

@bcamper the white buildings with dark gray grid is perfect, just trying to fix the colored buildings
sorry not clear earlier
