### ISSUE TITLE
Missing stream line (but it's labeled)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/refill#58]
14/39.4063/-77.4749

<img width="538" alt="screen shot 2017-06-08 at 17 50 03" src="https://user-images.githubusercontent.com/853051/26956485-ece5f062-4c72-11e7-8c9d-5005d5b127aa.png">

**Comment by sensescape** [comment]
fixed:
<img width="956" alt="screen shot 2017-06-29 at 11 12 50 am" src="https://user-images.githubusercontent.com/466585/27703355-f074d3c0-5cbb-11e7-9d7d-10aa0533a396.png">
http://localhost:8000/#14/13.5207/-1167.7555
<img width="516" alt="screen shot 2017-06-29 at 11 13 57 am" src="https://user-images.githubusercontent.com/466585/27703414-21d3b9c2-5cbc-11e7-9b37-3fc29ee6fd3e.png">
