### ISSUE TITLE
City labels collide because of a debug preference set

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/refill#68]
Resolved in bubble-wrap: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style.yaml#L4176
But not here: https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L4098

![screen shot 2017-08-18 at 3 20 23 pm](https://user-images.githubusercontent.com/360641/29479724-cc97b118-8428-11e7-93f4-e91f9e9adaa3.png)

cc. @nvkelso

**Comment by nvkelso** [comment]
Thanks! This one fell through the cracks when the problem was first reported. Fixed now in https://github.com/tangrams/refill-style/commit/445338fa70dc59577c4c0a9682a69f2001ae2d1d.
