### ISSUE TITLE
Source nextzen terrain tiles

### ISSUE THREAD

**Issue by nvkelso** [tangrams/refill#89]
The base style seems to do it right:

- https://github.com/tangrams/refill-style/blob/v11.0.0-docs1/refill-style.yaml#L255-L270

But then the terrain themes override that with the old Mapzen sources:

- https://github.com/tangrams/refill-style/blob/v11.0.0-docs1/themes/terrain-pattern-dark.yaml#L5-L10
- https://github.com/tangrams/refill-style/blob/v11.0.0-docs1/themes/terrain-pattern.yaml#L5-L10
- https://github.com/tangrams/refill-style/blob/v11.0.0-docs1/themes/terrain-shading-dark.yaml#L5-L11
- https://github.com/tangrams/refill-style/blob/v11.0.0-docs1/themes/terrain-shading.yaml#L5-L11

Attention should also be taken towards 512 px tile sizes and max source zooms, though. @iandees did we get [Zaloa](https://github.com/tilezen/zaloa) running in Tilezen?

**Comment by sensescape** [comment]
this is done
